version: '3.8'

services:
  api-gateway:
    build:
      context: .
      dockerfile: Dockerfile
    image: fleet-management/api-gateway:latest
    container_name: fleet-api-gateway
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=development
      - PORT=8080
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - LOG_LEVEL=debug
      - ENABLE_GLOBAL_RATE_LIMIT=true
      - INSTANCE_ID=api-gateway-1
      - REDIS_CONNECT_RETRIES=10
      - REDIS_CONNECT_RETRY_DELAY=2000
      - REDIS_STORE_RETRIES=5
      - VEHICLE_SERVICE_URL=http://vehicle-service:3000
      - TRACKING_SERVICE_URL=http://tracking-service:3002
    depends_on:
      redis:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - fleet-network
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:8080/api/gateway/health"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s

  redis:
    image: redis:7-alpine
    container_name: fleet-redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    command: redis-server --appendonly yes --maxmemory 256mb --maxmemory-policy allkeys-lru
    restart: unless-stopped
    networks:
      - fleet-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s
    deploy:
      resources:
        limits:
          memory: 300M

networks:
  fleet-network:
    driver: bridge

volumes:
  redis-data: 