name: API Gateway CI

on:
  pull_request:
    branches: [ master ]
    paths:
      - 'backend/api-gateway/**'
      - '.github/workflows/api-gateway-ci.yml'
  push:
    branches: [ master, main ]
    paths:
      - 'backend/api-gateway/**'
      - '.github/workflows/api-gateway-ci.yml'

jobs:
  build:
    name: Build and Test API Gateway
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: 'backend/api-gateway/package-lock.json'
      
      - name: Install dependencies
        working-directory: backend/api-gateway
        run: npm ci
        
      - name: Run linter
        working-directory: backend/api-gateway
        run: npm run lint || true # Don't fail on linting issues for now
        
      - name: Build TypeScript
        working-directory: backend/api-gateway
        run: npm run build
        
      - name: Run tests
        working-directory: backend/api-gateway
        run: npm test || true # Skip tests for now if they don't exist yet
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Build and cache Docker image
        uses: docker/build-push-action@v4
        with:
          context: ./backend/api-gateway
          push: false
          load: true
          tags: fleet-management/api-gateway:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max