name: API Gateway CI

on:
  pull_request:
    branches: [ master ]
    paths:
      - 'backend/api-gateway/**'
      - '.github/workflows/api-gateway-ci.yml'
  push:
    branches: [ master, main ]
    paths:
      - 'backend/api-gateway/**'
      - '.github/workflows/api-gateway-ci.yml'

jobs:
  build:
    name: Build and Test API Gateway
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: 'backend/api-gateway/package-lock.json'
      
      - name: Install dependencies
        working-directory: backend/api-gateway
        run: npm ci
        
      - name: Run linter
        working-directory: backend/api-gateway
        run: npm run lint
        
      - name: Build TypeScript
        working-directory: backend/api-gateway
        run: npm run build
        
      - name: Run tests with coverage
        working-directory: backend/api-gateway
        run: npm run test:ci
        
      - name: Upload test results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-results
          path: backend/api-gateway/test-results/junit.xml
          
      - name: Upload coverage report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: backend/api-gateway/coverage
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Build Docker image with tests
        uses: docker/build-push-action@v5
        with:
          context: ./backend/api-gateway
          target: test
          push: false
          load: false
          cache-from: type=gha
          cache-to: type=gha,mode=max
      
      - name: Build production Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./backend/api-gateway
          target: production
          push: false
          load: true
          tags: fleet-management/api-gateway:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max